# Generated by Django 2.2.6 on 2020-04-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='birth_date',
            new_name='formation_date',
        ),
    ]
