# Generated by Django 2.2.6 on 2020-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200428_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='blurb',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
